### ISSUE TITLE
How to disable certain checks?

### ISSUE THREAD

**Issue by jankrieg** [SAP/ui5-linter#129]
Hi guys,

I got this one:
"idVehicleTableTitle" should match pattern: "/^idVehicleItems.*?Title$/"TagAttributeLinter(UI5plugin)

 How can I change/disable existing checks?

Thanks,
Jan

**Comment by codeworrior** [comment]
HI Jan, 

the `TagAttributeLinter` is not part of the UI5 Linter. I guess you should refer [this project](to https://github.com/iljapostnovs/ui5plugin-linter?tab=readme-ov-file#tagattributelinter).
