### ISSUE TITLE
Option to use a different yaml file

### ISSUE THREAD

**Issue by marianfoo** [SAP/ui5-linter#144]
## Is your feature request related to a problem? Please describe.

I´d like to run the ui5-linter for my Component. Out of the box this does not work because of the `type: module` in my `ui5.yaml` file. Because of this i think this is more a feature request then bug.

Recreate the problem:
```bash
git clone https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter
cd packages/ui5-cc-spreadsheetimporter
ui5lint
```

Output when i run `ui5lint`:

```bash

⚠️  Process Failed With Error

Error Message:
Projects of type module have more than one source path
```

Error comes from https://github.com/SAP/ui5-project/blob/a085232514ebdd8ad11f5fd49323b0c0bb5c240b/lib/specifications/types/Module.js#L31

## Describe the solution you'd like

I use the middleware [`ui5-middleware-ui5`](https://www.npmjs.com/package/ui5-middleware-ui5) to use the Component in my UI5 App, so use a special yaml file for this anyway [ui5-serve.yaml](https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/blob/main/packages/ui5-cc-spreadsheetimporter/ui5-serve.yaml) change the type to `application`.

Most simple solution would that there would be a option so i can use the `ui5-serve.yaml` instead of the default `ui5.yaml`. I did not see the option in the cli yet.
Something like `ui5lint --configFile ui5-serve.yaml`

## Additional context

I think i need to change my type in the `ui5.yaml` anyway, because `application` fits better to my project, right?
Either way, a option to change the default yaml file would be great

**Comment by RandomByte** [comment]
This is a very reasonable enhancement.

We could also add support for projects of type `module`. But from what I can see this still wouldn't help you since your `ui5.yaml` only refers to the build result and not the sources (which you would probably want to lint).

> I think i need to change my type in the ui5.yaml anyway, because application fits better to my project, right?

I think this is yet another case where the Component type would be a good fit: https://github.com/SAP/ui5-tooling/issues/45

Thanks for reporting!

**Comment by marianfoo** [comment]
Thank you for confirming the enhancement.

I know the issue and just now remember what I wanted to ask you at UI5con.
When is the Component Type coming? 😃
Would be perfect for 4.0 😉

**Comment by RandomByte** [comment]
See https://github.com/SAP/ui5-tooling/issues/45#issuecomment-2152106687 😉

**Comment by marianfoo** [comment]
> See [SAP/ui5-tooling#45 (comment)](https://github.com/SAP/ui5-tooling/issues/45#issuecomment-2152106687) 😉

Would be great to see it in 4.X :)
If you need any help or testing this feature just shout out

**Comment by matz3** [comment]
Internal reference: CPOUI5FOUNDATION-855

**Comment by marianfoo** [comment]
fix #313

**Comment by flovogt** [comment]
and available with [v0.4.1](https://github.com/SAP/ui5-linter/releases/tag/v0.4.1).

**Comment by flovogt** [comment]
As long as we are in the pre `v1` release phase. We release bug fixes and non breaking features as patch releases. Only breaking changes we release as a minor release. 

https://github.com/SAP/ui5-linter/blob/main/release-please-config.json#L7C1-L8C43

**Comment by marianfoo** [comment]
Interesting, i bumped minor for features and breaking changes when i was pre-major. Not a big difference to me, comes down to personal preference.

**Comment by flovogt** [comment]
we thought this way its easier to highlight breaking changes.

**Comment by marianfoo** [comment]
Yes, makes sense, I didn't have that many breaking changes so I wanted to highlight new features :)
