### ISSUE TITLE
Feature request: Ignore file

### ISSUE THREAD

**Issue by Leoooob** [SAP/ui5-linter#170]
Running the linter today, you can specify specific files, but not folders to lint. It doesn't make sense to expand file paths to allow folders, it _does_ make sense that we should be able to set an ignore file to ignore generated files like the `component.js` for instance, or 3rd-party code and libraries.

The workaround right now is to specify every individual file in the project to be linted, which is a bit tedious but works for now.

I would prefer to be able to set a global ignore file for use across projects.

**Comment by matz3** [comment]
@Leoooob from your description I understand that it would be sufficient to only ignore on a file-level, not ignoring specific findings within a file, right?

**Comment by Leoooob** [comment]
Yes, that's correct.



Regards,

Leon



---- On Fri, 12 Jul 2024 14:08:09 +0100 ***@***.*** wrote ----



@Leoooob from your description I understand that it would be sufficient to only ignore on a file-level, not ignoring specific findings within a file, right?

**Comment by marianfoo** [comment]
Would be great to exclude directories as well, just not specific files like `webapp/test/*`

**Comment by flovogt** [comment]
This feature is implemented with https://github.com/SAP/ui5-linter/pull/264
