### ISSUE TITLE
New format option "markdown" for displaying linter reports as comments in pull requests

### ISSUE THREAD

**Issue by marcelschork** [SAP/ui5-linter#178]
## Is your feature request related to a problem? Please describe.

As of now it is only possibe to display the linter reports as text style comments in pull requests (see #175). 

## Describe the solution you'd like

For better readability and interactivity (links to documentation, API reference, ...) it would be great to have a markdown style output that can be just displayed as is in the comment section of pull requests. Therefore a new format option `markdown` could be introduced that ensures proper output of the linter results in markdown.

**Comment by marianfoo** [comment]
@marcelschork have a look at #258 , would that work?

**Comment by marcelschork** [comment]
@marianfoo looks great actually. I jchecked the markdown output, but this is exactly what I would expect. Just one thing in the file path / file name. There is a "double slash" in your sample output.

**/Users/marianzeis/DEV//webapp/util/Util.ts**

**Comment by marianfoo** [comment]
the "double slash" is just because i removed to the sensitive path wrong, it´s not there usually
But i agree, the full path does not make sense to me either, i think i will change it as in the JSON output, lets wait for the feedback from the team
