### ISSUE TITLE
Unsupported platform (os) when adding ui5linter to CAP project and running mbt build

### ISSUE THREAD

**Issue by bkrencker** [SAP/ui5-linter#24]
**Steps to reproduce:**
I added ui5linter to my CAP project using 
`npm install --save-dev @ui5/linter`

There is an error when building the CAP project:
`mbt build -p=cf`

**Error Message (root cause)**
`Unsupported platform for @esbuild/aix-ppc64@0.19.12: wanted {"os":"aix","cpu":"ppc64"} (current: {"os":"win32","cpu":"x64"})`

**Error Message (full)**
`[2024-03-13 18:56:19]  INFO executing the "npm clean-install --production" command...
npm WARN config production Use `--omit=dev` instead.
.npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@ui5/linter@0.1.0',
npm WARN EBADENGINE   required: { node: '^18.14.2 || ^20.11.0 || >=21.2.0', npm: '>= 9.5.0' },
npm WARN EBADENGINE   current: { node: 'v20.9.0', npm: '10.4.0' }
npm WARN EBADENGINE }
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @esbuild/aix-ppc64@0.19.12: wanted {"os":"aix","cpu":"ppc64"} (current: {"os":"win32","cpu":"x64"})
npm ERR! notsup Valid os:   aix
npm ERR! notsup Actual os:  win32
npm ERR! notsup Valid cpu:  ppc64
npm ERR! notsup Actual cpu: x64`

**Reason:**
In **package-lock.json** there is following dependency which came from ui5linter installation. This esbuild library has "aix" defined as operating system (os):
`    "node_modules/@ui5/linter/node_modules/@esbuild/aix-ppc64": {
      "version": "0.19.12",
      "resolved": "https://registry.npmjs.org/@esbuild/aix-ppc64/-/aix-ppc64-0.19.12.tgz",
      "integrity": "sha512-bmoCYyWdEL3wDQIVbcyzRyeKLgk2WtWLTWz1ZIAZF/EGbNOwSA6ew3PftJ1PqMiOOGu0OyFMzG53L0zqIpPeNA==",
      "cpu": [
        "ppc64"
      ],
      "extraneous": true,
      "os": [
        "aix"
      ],
      "engines": {
        "node": ">=12"
      }
    }`

**Comment by RandomByte** [comment]
Thank you for reporting this @bkrencker. This sounds like what we experienced in UI5 Tooling too: https://github.com/SAP/ui5-tooling/issues/283

Somehow `devDependencies` are installed when installing the ui5-linter package as a dependency. We'll need to adapt our release process the same way we did for UI5 Tooling. Sorry for the inconvenience.

CC: @flovogt

**Comment by RandomByte** [comment]
Reopening until a new release has been created
