### ISSUE TITLE
Ignore a specific line in code like `@ts-ignore`

### ISSUE THREAD

**Issue by marianfoo** [SAP/ui5-linter#268]
## Is your feature request related to a problem? Please describe.

If you want to develop a application for cross main version support, you need to use deprecated APIs. 
For example in this code sample to use `MessageManager` from Version 1.71 to 2.0 i still need to use the `sap.ui.getCore()`:

```ts
try {
	// sap.ui.core.Messaging is only available in UI5 version 1.118 and above, prefer this over sap.ui.getCore().getMessageManager()saging = Util.loadUI5RessourceAsync("sap/ui/core/Messaging");
	const Messaging = await Util.loadUI5RessourceAsync("sap/ui/core/Messaging");
	Messaging.removeAllMessages();
	return;
} catch (error) {
	Log.debug("sap/ui/core/Messaging not found", undefined, "SpreadsheetUpload: checkForODataErrors");
}
// fallback for UI5 versions below 1.118
sap.ui.getCore().getMessageManager().removeAllMessages();
```

## Describe the solution you'd like

When i would use the ui5 linter, this would be a error everytime the file is checked. So ignore file like in #170 does not help.  
I would like to use something like a annotation similar to for example `@ts-ignore`
In this case i can run CI/CD pipelines explicity stating that this can be ignored.

## Describe alternatives you've considered

Currently i don´t know how to workaround this.

**Comment by flovogt** [comment]
Thanks a lot @marianfoo for this enhancement. We will implement this feature in backlog item CPOUI5FOUNDATION-911.

**Comment by marianfoo** [comment]
@RandomByte yeah 🚀
finally i can include ui5 linter in my pipelines :D 
is the release for `1.3.0` today or tomorrow? ;)

**Comment by matz3** [comment]
It has just been released: https://github.com/SAP/ui5-linter/releases/tag/v1.3.0

**Comment by marianfoo** [comment]
I was pessimistic :D
thanks for your work
