### ISSUE TITLE
README outdated after v1.0.0

### ISSUE THREAD

**Issue by xLexip** [SAP/ui5-linter#332]
Hey there,

the `--file-paths `option is still in the README, even though it was removed with **v1.0.0**. 
https://github.com/SAP/ui5-linter?tab=readme-ov-file#--file-paths

Additional, it would be nice to explicitly list the change from `--file-paths` to the _files_ positional as a breaking change in the release notes. Our pipelines ran with Anlauf into error. :)

Best regards,
Lexip

**Comment by RandomByte** [comment]
Many thanks for letting us know! Indeed we missed that update. Will be fixed soon.
