### ISSUE TITLE
` ui5-linter` vs. `eslint-plugin-ui5depchk`

### ISSUE THREAD

**Issue by pubmikeb** [SAP/ui5-linter#363]
Could you please add a comparison table of  [`ui5-linter`](https://npmjs.com/package/@ui5/linter) vs. [`eslint-plugin-ui5depchk`](https://npmjs.com/package/eslint-plugin-ui5depchk).

It looks like both projects are alive and it would be interesting to see the difference between the two solutions.

**Comment by flovogt** [comment]
`ui5-linter` is an open-source project maintained by SAP SE offering checks for:
- Usage of deprecated UI5 libraries 
- Usage of deprecated UI5 framework APIs 
- Usage of global variables 
- Possible CSP violations 
- Deprecated component and manifest configurations

As far as I see [eslint-plugin-ui5depchk](https://npmjs.com/package/eslint-plugin-ui5depchk) uses https://ui5.sap.com/docs/api/api-index-deprecated.json as the "data base" which contains only deprecated modules and methods. Partially deprecated APIs are not considered here.
